# Generated by Django 4.1.7 on 2023-04-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_tiquetera"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="telefono",
        ),
    ]
