# Generated by Django 4.1.7 on 2023-04-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0002_alter_restaurante_nit_alter_restaurante_tipo_and_more"),
        ("clientes", "0003_remove_cliente_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="id_restaurante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurantes.restauranteusuario",
            ),
        ),
        migrations.AlterField(
            model_name="tiquetera",
            name="id_restaurante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurantes.restauranteusuario",
            ),
        ),
    ]
