# Generated by Django 4.1.7 on 2023-03-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurantes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=200)),
                ("precio", models.IntegerField()),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("Lunes", "Lunes"),
                            ("Martes", "Martes"),
                            ("Miércoles", "Miércoles"),
                            ("Jueves", "Jueves"),
                            ("Viernes", "Viernes"),
                            ("Sábado", "Sábado"),
                            ("Domingo", "Domingo"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "id_restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurantes.restaurante",
                    ),
                ),
            ],
        ),
    ]
