# Generated by Django 4.1.7 on 2023-04-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_alter_menu_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="dia",
            field=models.CharField(
                choices=[
                    ("Lunes", "Lunes"),
                    ("Martes", "Martes"),
                    ("Miércoles", "Miércoles"),
                    ("Jueves", "Jueves"),
                    ("Viernes", "Viernes"),
                    ("Sábado", "Sábado"),
                    ("Domingo", "Domingo"),
                    ("Diarion", "Diario"),
                ],
                max_length=10,
            ),
        ),
    ]
