# Generated by Django 4.1.7 on 2023-04-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0004_alter_menu_dia"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="dia",
            new_name="dia1",
        ),
        migrations.AddField(
            model_name="menu",
            name="dia2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Lunes", "Lunes"),
                    ("Martes", "Martes"),
                    ("Miércoles", "Miércoles"),
                    ("Jueves", "Jueves"),
                    ("Viernes", "Viernes"),
                    ("Sábado", "Sábado"),
                    ("Domingo", "Domingo"),
                    ("Diario", "Diario"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="dia3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Lunes", "Lunes"),
                    ("Martes", "Martes"),
                    ("Miércoles", "Miércoles"),
                    ("Jueves", "Jueves"),
                    ("Viernes", "Viernes"),
                    ("Sábado", "Sábado"),
                    ("Domingo", "Domingo"),
                    ("Diario", "Diario"),
                ],
                max_length=10,
            ),
        ),
    ]
