# Generated by Django 4.1.7 on 2023-04-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0005_rename_dia_menu_dia1_menu_dia2_menu_dia3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="dia2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Lunes", "Lunes"),
                    ("Martes", "Martes"),
                    ("Miércoles", "Miércoles"),
                    ("Jueves", "Jueves"),
                    ("Viernes", "Viernes"),
                    ("Sábado", "Sábado"),
                    ("Domingo", "Domingo"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="dia3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Lunes", "Lunes"),
                    ("Martes", "Martes"),
                    ("Miércoles", "Miércoles"),
                    ("Jueves", "Jueves"),
                    ("Viernes", "Viernes"),
                    ("Sábado", "Sábado"),
                    ("Domingo", "Domingo"),
                ],
                max_length=10,
            ),
        ),
    ]
