# Generated by Django 4.1.7 on 2023-04-09 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0002_alter_restaurante_nit_alter_restaurante_tipo_and_more"),
        ("menus", "0006_alter_menu_dia2_alter_menu_dia3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="id_restaurante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurantes.restauranteusuario",
            ),
        ),
    ]
