# Generated by Django 4.1.7 on 2023-04-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0007_alter_menu_id_restaurante"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="dia1",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="dia2",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="dia3",
        ),
        migrations.AddField(
            model_name="menu",
            name="domingo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menu",
            name="jueves",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menu",
            name="lunes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menu",
            name="martes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menu",
            name="miercoles",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menu",
            name="sabado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menu",
            name="viernes",
            field=models.BooleanField(default=False),
        ),
    ]
