# Generated by Django 4.1.7 on 2023-04-26 19:47

from django.db import migrations, models
import menus.models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0009_remove_menu_precio"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="imagen",
            field=models.ImageField(
                blank=True,
                upload_to="menu_imagenes/",
                validators=[menus.models.validate_image_extension],
            ),
        ),
    ]
