# Generated by Django 4.1.7 on 2023-04-26 20:50

from django.db import migrations, models
import menus.models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0010_menu_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="imagen",
            field=models.ImageField(
                blank=True,
                upload_to="menu_imagenes",
                validators=[menus.models.validate_image_extension],
            ),
        ),
    ]
