# Generated by Django 4.1.7 on 2023-04-03 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurantes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurante",
            name="NIT",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="restaurante",
            name="tipo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="RestauranteUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("NIT", models.CharField(blank=True, max_length=20)),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=20)),
                ("tipo", models.CharField(blank=True, max_length=100)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
