# Generated by Django 4.1.7 on 2023-04-27 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0002_alter_restaurante_nit_alter_restaurante_tipo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TiqueteraVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("precio", models.IntegerField()),
                (
                    "id_restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurantes.restauranteusuario",
                    ),
                ),
            ],
        ),
    ]
